### ISSUE TITLE
New framework: HTMZ

### ISSUE THREAD

**Issue by deejayy** [cuvar/days-since-js-framework#3]
Does this qualify?
https://github.com/Kalabasa/htmz

**Comment by cuvar** [comment]
Hi @deejayy , thanks! I already stumbled upon that. For me, the question is whether this is a _JavaScript_ framework. It states on the website: "HTML microframework" and "create modular web user interfaces with the familiar simplicity of plain HTML". Currently, I'd not include it, but I'll maybe open up a new category soon.
